
'use client';
// This file is automatically generated. Do not modify it manually.

import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth, Auth } from 'firebase/auth';
import { getFirestore, Firestore } from 'firebase/firestore';
import { getFirebaseConfig } from './config';

let app: FirebaseApp;
let auth: Auth;
let firestore: Firestore;

function initializeServices() {
  const firebaseConfig = getFirebaseConfig();
  if (!getApps().length) {
    app = initializeApp(firebaseConfig);
  } else {
    app = getApp();
  }
  auth = getAuth(app);
  firestore = getFirestore(app);

  return { app, auth, firestore };
}

// This function has been modified to ensure it only runs on the client-side.
export function getFirebaseServices() {
  if (typeof window === 'undefined') {
    // This is a mock for server-side rendering to avoid errors.
    // The actual initialization will happen on the client.
    return {
      app: null,
      auth: null,
      firestore: null,
    };
  }
  if (!app) {
    return initializeServices();
  }
  return { app, auth, firestore };
}
